site_name: Документация
site_url: https://vera-banderovskaya.github.io/my-docs/

nav:
  - Главная: index.md
  - О проекте: about.md
  - Инструкции:
    - "MkDocs": instructions/mkdocs-guide.md
    - "Git": instructions/git-guide.md

plugins:
  - search:
      separator: '[\s\-\.]+'
      min_search_length: 2

theme:
  name: material
  features:
    # Убираем ненужные функции поиска
    - search.highlight  # Оставляем только подсветку результатов
    # - search.suggest  # Убираем "паутину"
    # - search.share    # Убираем кнопку "поделиться"

markdown_extensions:
  - toc:
      permalink: false  # Полностью отключаем якоря
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css