site_name: Документация
site_url: https://vera-banderovskaya.github.io/my-docs/

nav:
  - Главная: index.md
  - Инструкции:
    - "MkDocs": instructions/mkdocs-guide.md
    - "Git": instructions/git-guide.md
  - О проекте: about.md

plugins:
  - search:
      separator: '[\s\-\.]+'
      min_search_length: 2

theme:
  name: material
  custom_dir: docs/overrides  # ПЕРЕМЕЩЕНО НА ПРАВИЛЬНОЕ МЕСТО
  features:
    - search.highlight  # Оставляем только подсветку результатов
    # Для полного отключения ненужных функций лучше удалить строки, а не комментировать

markdown_extensions:
  - toc:
      permalink: false  # Полностью отключаем якоря
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/search-i18n.js