site_name: Документация
site_url: https://vera-banderovskaya.github.io/my-docs/

nav:
  - Главная: index.md
  - Инструкции:
    - "MkDocs": instructions/mkdocs-guide.md
    - "Git": instructions/git-guide.md
  - О проекте: about.md

plugins:
  - search:
      separator: '[\s\-\.]+'
      min_search_length: 2
      lang: ru  # ДОБАВЛЕНО для русского поиска

theme:
  name: material
  language: ru  # ДОБАВЛЕНО для русского интерфейса
  features:
    - search.highlight
  # УДАЛЕНО custom_dir: docs/overrides - эта строка больше не нужна

markdown_extensions:
  - toc:
      permalink: false
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/search-i18n.js  # Оставляем только этот JavaScript