site_name: Документация
site_url: https://vera-banderovskaya.github.io/my-docs/

nav:
  - Главная: index.md
  - Инструкции:
    - "MkDocs": instructions/mkdocs-guide.md
    - "Docker": instructions/docker.md
    - "Git": instructions/git-guide.md
  - О проекте: about.md

plugins:
  - search:
      separator: '[\s\-\.]+'
      # min_search_length: 2  # УДАЛЕНО (устаревшая опция в новых версиях Material)
      lang: ru
      # Новые рекомендуемые параметры для поиска:
      prebuild_index: true
      indexing: 'full'

theme:
  name: material
  language: ru
  features:
    - search.highlight
    - search.suggest
    - search.share

markdown_extensions:
  - toc:
      permalink: false
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - attr_list  # Для расширенной работы с атрибутами

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/search-i18n.js