site_name: Документация
site_url: https://vera-banderovskaya.github.io/my-docs/

nav:
  - Главная: index.md
  - О проекте: about.md
  - Инструкции:
    - "MkDocs": instructions/mkdocs-guide.md
    - "Git": instructions/git-guide.md

plugins:
  - search:
      separator: '[\s\-\.]+'
      min_search_length: 2

theme:
  name: material
  features:
    - search.highlight
    - search.suggest
    - search.share

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.superfences